version: '3'

services:
  postgres:
    image: postgres:10
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cats_db
    ports:
      - 5432:5432

  app:
    build: ./app
    container_name: app
#    volumes:
#      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres